options:
  machineType: N1_HIGHCPU_32
steps:
- name: 'ubuntu'
  id: 'decrypt'
  entrypoint: 'bash'
  env:
    - "ENC_ITER=${_ENC_ITER}"
    - "ENC_PASS=${_ENC_PASS}"
  args:
  - '-c'
  - |
    if [ -n "${_TEST}" ]; then
      apt update && apt install -y openssl
      sh scripts/decrypt.sh
    fi
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      docker build -t ${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8) .
    fi
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
    - "DEBIAN_FRONTEND=noninteractive"
    - "AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}"
    - "AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION}"
  args: 
  - '-c'
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      apt update && apt install -y unzip python &&
      curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" &&
      unzip awscli-bundle.zip &&
      ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws &&
      aws ecr get-login-password | docker login --username AWS --password-stdin ${_DOCKER_REPO_URL}
      docker push ${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8)
    fi
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  env:
    - "AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}"
    - "AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION}"
  args:
  - '-c'
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws &&
      aws eks update-kubeconfig --name ${_CLUSTER} --region=${_AWS_DEFAULT_REGION} &&
      kubectl -n ${_NAMESPACE} set image deployment/${_DEPLOYMENT} ${_DEPLOYMENT}=${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8)
    fi
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-up'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    if [ -n "${_TEST}" ]; then
      set -e
      curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose &&
      docker-compose -f ./docker-compose-tests.yml build && 
      docker-compose -f ./docker-compose-tests.yml up --exit-code-from pakkasmarja-tests
    fi
timeout: 900s
