steps:
- name: 'ubuntu'
  id: test-data
  entrypoint: 'bash'
  env:
    - "ENC_ITER=${_ENC_ITER}"
    - "ENC_PASS=${_ENC_PASS}"
  args:
  - '-c'
  - |
    if [ -n "${_TEST}" ]; then
      apt update && apt install -y openssl
      sh scripts/decrypt.sh
    fi
- name: 'ubuntu'
  id: 'docker-up'
  waitFor: [ 'test-data' ]
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    if [ -n "${_TEST}" ]; then
      apt-get update
      apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update
      apt-get install docker-ce docker-ce-cli containerd.io
      curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
      docker-compose build
      docker-compose up
    fi
- name: 'node:dubnium'
  waitFor: [ 'test-data' ]
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ -n "${_TEST}" ]; then
        sh scripts/wait-api.sh
        npm run test
      fi
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-build'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      docker build -t ${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8) .
    fi
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
    - "DEBIAN_FRONTEND=noninteractive"
    - "AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}"
    - "AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION}"
  args: 
  - '-c'
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      apt update && apt install -y unzip python &&
      curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" &&
      unzip awscli-bundle.zip &&
      ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws &&
      aws ecr get-login-password | docker login --username AWS --password-stdin ${_DOCKER_REPO_URL}
      docker push ${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8)
    fi
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  env:
    - "AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}"
    - "AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION}"
  args:
  - '-c'
  - |
    if [ -n "${_DEPLOYMENT}" ]; then
      ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws &&
      aws eks update-kubeconfig --name ${_CLUSTER} --region=${_AWS_DEFAULT_REGION} &&
      kubectl -n ${_NAMESPACE} set image deployment/${_DEPLOYMENT} ${_DEPLOYMENT}=${_DOCKER_REPO_URL}:$(echo ${BUILD_ID} | cut -b 1-8)
    fi