FROM node:dubnium
WORKDIR /usr/src/pakkasmarja
ADD . .
COPY package*.json ./
RUN npm install
RUN npm run build
ADD ./docker/run-tests.sh /opt/docker/run-tests.sh
RUN chmod a+x /opt/docker/run-tests.sh
CMD "/opt/docker/run-tests.sh"
