/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BasicContact { 
    id: string  | null;
    readonly displayName: string  | null;
    readonly avatarUrl: string  | null;
}    

export interface BasicContactOpt { 
    id?: string;
    readonly displayName?: string;
    readonly avatarUrl?: string;
}
