/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatGroupPermissionScope } from './chatGroupPermissionScope';


export interface ChatGroupUserPermission { 
    id: string  | null;
    chatGroupId: number  | null;
    userId: string  | null;
    scope: ChatGroupPermissionScope  | null;
}    

export interface ChatGroupUserPermissionOpt { 
    id?: string;
    chatGroupId?: number;
    userId?: string;
    scope?: ChatGroupPermissionScope;
}
