/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatThreadPermissionScope } from './chatThreadPermissionScope';


export interface ChatThreadUserPermission { 
    id: string  | null;
    chatThreadId: number  | null;
    userId: string  | null;
    scope: ChatThreadPermissionScope  | null;
}    

export interface ChatThreadUserPermissionOpt { 
    id?: string;
    chatThreadId?: number;
    userId?: string;
    scope?: ChatThreadPermissionScope;
}
