/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatGroupType } from './chatGroupType';


export interface ChatGroup { 
    id: number  | null;
    type: ChatGroupType ;
    title: string ;
    imageUrl: string  | null;
}    

export interface ChatGroupOpt { 
    id?: number;
    type?: ChatGroupType;
    title?: string;
    imageUrl?: string;
}
