/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Contract } from './contract';
import { ContractPreview } from './contractPreview';
import { ContractPreviewError } from './contractPreviewError';


export interface ContractPreviewData { 
    contract: Contract ;
    preview: ContractPreview ;
    errors: Array<ContractPreviewError> ;
}    

export interface ContractPreviewDataOpt { 
    contract?: Contract;
    preview?: ContractPreview;
    errors?: Array<ContractPreviewError>;
}
