/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AreaDetail } from './areaDetail';


export interface Contract { 
    id: string  | null;
    sapId: string  | null;
    contactId: string  | null;
    deliveryPlaceId: string  | null;
    proposedDeliveryPlaceId: string  | null;
    deliveryPlaceComment: string  | null;
    itemGroupId: string  | null;
    year: number ;
    contractQuantity: number  | null;
    deliveredQuantity: number  | null;
    proposedQuantity: number  | null;
    quantityComment: string  | null;
    startDate: Date  | null;
    endDate: Date  | null;
    signDate: Date  | null;
    termDate: Date  | null;
    rejectComment: string  | null;
    areaDetails: Array<AreaDetail>  | null;
    deliverAll: boolean ;
    status: Contract.StatusEnum ;
    remarks: string  | null;
}    

export interface ContractOpt { 
    id?: string;
    sapId?: string;
    contactId?: string;
    deliveryPlaceId?: string;
    proposedDeliveryPlaceId?: string;
    deliveryPlaceComment?: string;
    itemGroupId?: string;
    year?: number;
    contractQuantity?: number;
    deliveredQuantity?: number;
    proposedQuantity?: number;
    quantityComment?: string;
    startDate?: Date;
    endDate?: Date;
    signDate?: Date;
    termDate?: Date;
    rejectComment?: string;
    areaDetails?: Array<AreaDetail>;
    deliverAll?: boolean;
    status?: Contract.StatusEnum;
    remarks?: string;
}
export namespace Contract {
    export type StatusEnum = 'APPROVED' | 'ON_HOLD' | 'DRAFT' | 'TERMINATED' | 'REJECTED';
    export const StatusEnum = {
        APPROVED: 'APPROVED' as StatusEnum,
        ONHOLD: 'ON_HOLD' as StatusEnum,
        DRAFT: 'DRAFT' as StatusEnum,
        TERMINATED: 'TERMINATED' as StatusEnum,
        REJECTED: 'REJECTED' as StatusEnum
    };
}
