/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContractStatus } from './contractStatus';


export interface ContractPreview { 
    sapId: string ;
    contactName: string ;
    deliveryPlaceName: string ;
    deliveryPlaceComment: string ;
    itemGroupName: string ;
    year: number ;
    contractQuantity: number ;
    quantityComment: string ;
    deliverAll: boolean ;
    status: ContractStatus ;
    remarks: string ;
}    

export interface ContractPreviewOpt { 
    sapId?: string;
    contactName?: string;
    deliveryPlaceName?: string;
    deliveryPlaceComment?: string;
    itemGroupName?: string;
    year?: number;
    contractQuantity?: number;
    quantityComment?: string;
    deliverAll?: boolean;
    status?: ContractStatus;
    remarks?: string;
}
