/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OpeningHourException } from './openingHourException';
import { OpeningHourPeriod } from './openingHourPeriod';


export interface OpeningHours { 
    exceptions: Array<OpeningHourException>  | null;
    periods: Array<OpeningHourPeriod>  | null;
}    

export interface OpeningHoursOpt { 
    exceptions?: Array<OpeningHourException>;
    periods?: Array<OpeningHourPeriod>;
}
