/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OpeningHourInterval } from './openingHourInterval';


export interface OpeningHourException {
    id: string  | null;
    exceptionDate: Date ;
    hours: Array<OpeningHourInterval> ;
}

export interface OpeningHourExceptionOpt {
    id?: string;
    exceptionDate?: Date;
    hours?: Array<OpeningHourInterval>;
}
